[tool.poetry]
name = "symmer"
version = "0.1.0"
description = ""
authors = ["AlexisRalli <rallilex@hotmail.co.uk>", "TimWeaving <weaving.timothy@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
openfermion = "^1.3.0"
cached-property = "^1.5.2"
openfermionpyscf = "^0.5"
qiskit = "^0.38.0"
pydocstyle = "^6.1.1"
isort = "^5.10.1"
black = "^22.1.0"
flake8 = "^4.0.1"
py3Dmol = "^1.8.0"
pyzx = "^0.7.0"
h5py = "<=3.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
