name: CodeCov

on: [push]

jobs:
  build:
    name: Testing and Coverage
    
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v2
    - name: Set up python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Installation
      run: |
        python -m pip install --upgrade pip
        pip install .
    - name: Generate Report
      run: |
        pip install coverage
        pip install pytest
        coverage run -m pytest
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v2
